### ISSUE TITLE
Cannot Generate PLA (Left) and PVA (Right) Cura Profile

### ISSUE THREAD

**Issue by brian10salazar** [BCN3D/BCN3DSigma-Profile-Generator#4]
When trying to generate a Cura profile for Colorfila PLA with an 0.4mm nozzle on the left and Esum PVA with an 0.4 mm nozzle on the right, I get the following error

Profile for Cura
Traceback (most recent call last):
  File "SigmaProfileGenerator.py", line 1745, in <module>
    main() 
  File "SigmaProfileGenerator.py", line 1701, in main
    print "\n\tYour new Cura profile '"+createCuraProfile(sorted(profilesData['hotend'], key=lambda k: k['id'])[a[0]], sorted(profilesData['hotend'], key=lambda k: k['id'])[b[0]], sorted(profilesData['filament'], key=lambda k: k['id'])[a[1]], sorted(profilesData['filament'], key=lambda k: k['id'])[b[1]], sorted(profilesData['quality'], key=lambda k: k['index'])[c], dataLog, 'createFile')+"' has been created.\n"
  File "SigmaProfileGenerator.py", line 708, in createCuraProfile
    purgeValuesT1 = purgeValues(hotendRight, filamentRight, currentDefaultSpeed, currentLayerHeight)
  File "SigmaProfileGenerator.py", line 1133, in purgeValues
    maxPrintSpeed = ((temperatureValue(filament, hotend, layerHeight, speed) - filament['printTemperature'][0])/float(filament['printTemperature'][1]-filament['printTemperature'][0])) * maxFlowValue(hotend, filament) / (hotend['nozzleSize']*layerHeight/60)
ZeroDivisionError: float division by zero

**Comment by guillemap** [comment]
Thanks! Solved with v1.1.1
